package main

import (
	"github.com/amazon-transcribe-service/mcp-server/config"
	"github.com/amazon-transcribe-service/mcp-server/models"
	tools_x_amz_target_transcribe_getmedicalvocabulary "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_getmedicalvocabulary"
	tools_x_amz_target_transcribe_startmedicaltranscriptionjob "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_startmedicaltranscriptionjob"
	tools_x_amz_target_transcribe_updatevocabulary "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_updatevocabulary"
	tools_x_amz_target_transcribe_getvocabularyfilter "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_getvocabularyfilter"
	tools_x_amz_target_transcribe_updatevocabularyfilter "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_updatevocabularyfilter"
	tools_x_amz_target_transcribe_starttranscriptionjob "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_starttranscriptionjob"
	tools_x_amz_target_transcribe_listlanguagemodels "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_listlanguagemodels"
	tools_x_amz_target_transcribe_deletetranscriptionjob "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_deletetranscriptionjob"
	tools_x_amz_target_transcribe_listcallanalyticscategories "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_listcallanalyticscategories"
	tools_x_amz_target_transcribe_tagresource "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_tagresource"
	tools_x_amz_target_transcribe_updatecallanalyticscategory "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_updatecallanalyticscategory"
	tools_x_amz_target_transcribe_updatemedicalvocabulary "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_updatemedicalvocabulary"
	tools_x_amz_target_transcribe_gettranscriptionjob "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_gettranscriptionjob"
	tools_x_amz_target_transcribe_createvocabulary "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_createvocabulary"
	tools_x_amz_target_transcribe_startcallanalyticsjob "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_startcallanalyticsjob"
	tools_x_amz_target_transcribe_deletelanguagemodel "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_deletelanguagemodel"
	tools_x_amz_target_transcribe_createcallanalyticscategory "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_createcallanalyticscategory"
	tools_x_amz_target_transcribe_listcallanalyticsjobs "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_listcallanalyticsjobs"
	tools_x_amz_target_transcribe_deletevocabulary "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_deletevocabulary"
	tools_x_amz_target_transcribe_listmedicalvocabularies "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_listmedicalvocabularies"
	tools_x_amz_target_transcribe_deletecallanalyticscategory "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_deletecallanalyticscategory"
	tools_x_amz_target_transcribe_deletemedicalvocabulary "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_deletemedicalvocabulary"
	tools_x_amz_target_transcribe_deletecallanalyticsjob "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_deletecallanalyticsjob"
	tools_x_amz_target_transcribe_describelanguagemodel "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_describelanguagemodel"
	tools_x_amz_target_transcribe_createmedicalvocabulary "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_createmedicalvocabulary"
	tools_x_amz_target_transcribe_deletevocabularyfilter "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_deletevocabularyfilter"
	tools_x_amz_target_transcribe_listvocabularyfilters "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_listvocabularyfilters"
	tools_x_amz_target_transcribe_getmedicaltranscriptionjob "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_getmedicaltranscriptionjob"
	tools_x_amz_target_transcribe_listtranscriptionjobs "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_listtranscriptionjobs"
	tools_x_amz_target_transcribe_listtagsforresource "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_listtagsforresource"
	tools_x_amz_target_transcribe_getvocabulary "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_getvocabulary"
	tools_x_amz_target_transcribe_untagresource "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_untagresource"
	tools_x_amz_target_transcribe_deletemedicaltranscriptionjob "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_deletemedicaltranscriptionjob"
	tools_x_amz_target_transcribe_createvocabularyfilter "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_createvocabularyfilter"
	tools_x_amz_target_transcribe_listmedicaltranscriptionjobs "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_listmedicaltranscriptionjobs"
	tools_x_amz_target_transcribe_listvocabularies "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_listvocabularies"
	tools_x_amz_target_transcribe_createlanguagemodel "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_createlanguagemodel"
	tools_x_amz_target_transcribe_getcallanalyticsjob "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_getcallanalyticsjob"
	tools_x_amz_target_transcribe_getcallanalyticscategory "github.com/amazon-transcribe-service/mcp-server/tools/x_amz_target_transcribe_getcallanalyticscategory"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_transcribe_getmedicalvocabulary.CreateGetmedicalvocabularyTool(cfg),
		tools_x_amz_target_transcribe_startmedicaltranscriptionjob.CreateStartmedicaltranscriptionjobTool(cfg),
		tools_x_amz_target_transcribe_updatevocabulary.CreateUpdatevocabularyTool(cfg),
		tools_x_amz_target_transcribe_getvocabularyfilter.CreateGetvocabularyfilterTool(cfg),
		tools_x_amz_target_transcribe_updatevocabularyfilter.CreateUpdatevocabularyfilterTool(cfg),
		tools_x_amz_target_transcribe_starttranscriptionjob.CreateStarttranscriptionjobTool(cfg),
		tools_x_amz_target_transcribe_listlanguagemodels.CreateListlanguagemodelsTool(cfg),
		tools_x_amz_target_transcribe_deletetranscriptionjob.CreateDeletetranscriptionjobTool(cfg),
		tools_x_amz_target_transcribe_listcallanalyticscategories.CreateListcallanalyticscategoriesTool(cfg),
		tools_x_amz_target_transcribe_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_transcribe_updatecallanalyticscategory.CreateUpdatecallanalyticscategoryTool(cfg),
		tools_x_amz_target_transcribe_updatemedicalvocabulary.CreateUpdatemedicalvocabularyTool(cfg),
		tools_x_amz_target_transcribe_gettranscriptionjob.CreateGettranscriptionjobTool(cfg),
		tools_x_amz_target_transcribe_createvocabulary.CreateCreatevocabularyTool(cfg),
		tools_x_amz_target_transcribe_startcallanalyticsjob.CreateStartcallanalyticsjobTool(cfg),
		tools_x_amz_target_transcribe_deletelanguagemodel.CreateDeletelanguagemodelTool(cfg),
		tools_x_amz_target_transcribe_createcallanalyticscategory.CreateCreatecallanalyticscategoryTool(cfg),
		tools_x_amz_target_transcribe_listcallanalyticsjobs.CreateListcallanalyticsjobsTool(cfg),
		tools_x_amz_target_transcribe_deletevocabulary.CreateDeletevocabularyTool(cfg),
		tools_x_amz_target_transcribe_listmedicalvocabularies.CreateListmedicalvocabulariesTool(cfg),
		tools_x_amz_target_transcribe_deletecallanalyticscategory.CreateDeletecallanalyticscategoryTool(cfg),
		tools_x_amz_target_transcribe_deletemedicalvocabulary.CreateDeletemedicalvocabularyTool(cfg),
		tools_x_amz_target_transcribe_deletecallanalyticsjob.CreateDeletecallanalyticsjobTool(cfg),
		tools_x_amz_target_transcribe_describelanguagemodel.CreateDescribelanguagemodelTool(cfg),
		tools_x_amz_target_transcribe_createmedicalvocabulary.CreateCreatemedicalvocabularyTool(cfg),
		tools_x_amz_target_transcribe_deletevocabularyfilter.CreateDeletevocabularyfilterTool(cfg),
		tools_x_amz_target_transcribe_listvocabularyfilters.CreateListvocabularyfiltersTool(cfg),
		tools_x_amz_target_transcribe_getmedicaltranscriptionjob.CreateGetmedicaltranscriptionjobTool(cfg),
		tools_x_amz_target_transcribe_listtranscriptionjobs.CreateListtranscriptionjobsTool(cfg),
		tools_x_amz_target_transcribe_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_transcribe_getvocabulary.CreateGetvocabularyTool(cfg),
		tools_x_amz_target_transcribe_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_transcribe_deletemedicaltranscriptionjob.CreateDeletemedicaltranscriptionjobTool(cfg),
		tools_x_amz_target_transcribe_createvocabularyfilter.CreateCreatevocabularyfilterTool(cfg),
		tools_x_amz_target_transcribe_listmedicaltranscriptionjobs.CreateListmedicaltranscriptionjobsTool(cfg),
		tools_x_amz_target_transcribe_listvocabularies.CreateListvocabulariesTool(cfg),
		tools_x_amz_target_transcribe_createlanguagemodel.CreateCreatelanguagemodelTool(cfg),
		tools_x_amz_target_transcribe_getcallanalyticsjob.CreateGetcallanalyticsjobTool(cfg),
		tools_x_amz_target_transcribe_getcallanalyticscategory.CreateGetcallanalyticscategoryTool(cfg),
	}
}
